-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/", F.BOARD_ID, "/", F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS F
LEFT JOIN USED_GOODS_BOARD AS B
ON B.BOARD_ID = F.BOARD_ID
WHERE B.VIEWS = (
    SELECT MAX(B.VIEWS)
    FROM USED_GOODS_BOARD AS B
    )
ORDER BY F.FILE_NAME DESC

# SELECT
#     CONCAT('/home/grep/src/', FILE.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
# FROM USED_GOODS_FILE AS FILE
# LEFT JOIN USED_GOODS_BOARD AS BOARD
# ON FILE.BOARD_ID = BOARD.BOARD_ID
# WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
# ORDER BY FILE_ID DESC